name: money-flow-dev

services:
  nginx:
    container_name: nginx
    build:
      context: ../../
      dockerfile: ./deployments/dev/image/nginx.Dockerfile
    command: ["nginx", "-g", "daemon off;"]
    hostname: ${NGINX_HOST}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - DOMAIN_HOST=${DOMAIN_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started

  backend:
    container_name: backend
    build:
      context: ../../
      dockerfile: ./deployments/dev/image/backend.Dockerfile
    command:
      [
        "poetry",
        "run",
        "python",
        "src/manage.py",
        "runserver",
        "0.0.0.0:${BACKEND_PORT}",
      ]
    hostname: ${BACKEND_HOST}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./../../backend:/backend
    environment:
      - TZ=${TZ}
      - DOMAIN_HOST=${DOMAIN_HOST}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
    - ./conf/.env.backend.local
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    build:
      context: ../../
      dockerfile: ./deployments/dev/image/postgres.Dockerfile
    command: ["postgres", "-c", "port=${POSTGRES_PORT}"]
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - TZ=${TZ}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}",
          "-h",
          "${POSTGRES_HOST}",
          "-p",
          "${POSTGRES_PORT}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  pg-data:
