# Generated by Django 5.2.2 on 2025-06-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['INFRASTRUCTURE', 'MARKETING', 'SALARY'])), name='valid_category_name'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['BUSINESS', 'PERSONAL', 'TAX'])), name='valid_status_name'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['VPS', 'PROXY', 'FARPOST', 'AVITO'])), name='valid_subcategory_name'),
        ),
        migrations.AddConstraint(
            model_name='transactiontype',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['INCOME', 'EXPENSE'])), name='valid_transaction_type_name'),
        ),
    ]
