# Generated by Django 5.2.2 on 2025-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_alter_category_name_alter_status_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='valid_category_name',
        ),
        migrations.RemoveConstraint(
            model_name='status',
            name='valid_status_name',
        ),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='valid_subcategory_name',
        ),
        migrations.RemoveConstraint(
            model_name='transactiontype',
            name='valid_transaction_type_name',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['Infrastructure', 'Marketing', 'Salary'])), name='valid_category_name'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['Business', 'Personal', 'Tax'])), name='valid_status_name'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['VPS', 'Proxy', 'Farpost', 'Avito'])), name='valid_subcategory_name'),
        ),
        migrations.AddConstraint(
            model_name='transactiontype',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['Income', 'Expense'])), name='valid_transaction_type_name'),
        ),
    ]
