# Generated by Django 5.2.2 on 2025-06-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_remove_category_valid_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='valid_category_name',
        ),
        migrations.RemoveConstraint(
            model_name='status',
            name='valid_status_name',
        ),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='valid_subcategory_name',
        ),
        migrations.RemoveConstraint(
            model_name='transactiontype',
            name='valid_transaction_type_name',
        ),
    ]
