# Generated by Django 5.2.2 on 2025-06-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
