# Generated by Django 5.2.2 on 2025-06-13 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_remove_category_valid_category_name_and_more'),
        ('transactions', '0003_alter_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='reference.subcategory'),
        ),
    ]
