name: money-flow

services:
  nginx:
    container_name: nginx
    build:
      context: ../../
      dockerfile: ./deployments/prod/images/nginx.Dockerfile
    command: ["nginx", "-g", "daemon off;"]
    hostname: ${DOCKER_NGINX_HOST}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - static_files:/backend/staticfiles/
    environment:
      - TZ=${TZ}
      - NGINX_PORT=${NGINX_PORT}

      - DOCKER_NGINX_HOST=${DOCKER_NGINX_HOST}
      - DOCKER_BACKEND_HOST=${DOCKER_BACKEND_HOST}
      - DOCKER_FRONTEND_HOST=${DOCKER_FRONTEND_HOST}

      - BACKEND_BASE=${BACKEND_BASE}
      - FRONTEND_BASE=${FRONTEND_BASE}
      - DOCKER_BACKEND_PORT=${DOCKER_BACKEND_PORT}
      - DOCKER_FRONTEND_PORT=${DOCKER_FRONTEND_PORT}
    restart: unless-stopped
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started

  frontend:
    container_name: frontend
    build:
      context: ../../
      dockerfile: ./deployments/prod/images/frontend.Dockerfile
    command: ["node", "/nuxt/server/index.mjs"]
    hostname: ${DOCKER_FRONTEND_HOST}
    expose:
      - ${DOCKER_FRONTEND_PORT}
    environment:
      - HOST=${DOCKER_FRONTEND_HOST}
      - PORT=${DOCKER_FRONTEND_PORT}
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started

  backend:
    container_name: backend
    build:
      context: ../../
      dockerfile: ./deployments/prod/images/backend.Dockerfile
    command:
      [
        "poetry",
        "run",
        "gunicorn",
        "config.wsgi",
        "--preload",
        "--max-requests",
        "3000",
        "--max-requests-jitter",
        "1500",
        "--bind",
        "0.0.0.0:${DOCKER_BACKEND_PORT}",
        "--pid",
        "gunicorn.pid",
      ]
    hostname: ${DOCKER_BACKEND_HOST}
    expose:
      - ${DOCKER_BACKEND_PORT}
    volumes:
      - static_files:/backend/staticfiles/
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - BACKEND_BASE=${BACKEND_BASE}
      - FRONTEND_BASE=${FRONTEND_BASE}

      - DOCKER_BACKEND_HOST=${DOCKER_BACKEND_HOST}
      - DOCKER_POSTGRES_HOST=${DOCKER_POSTGRES_HOST}

      - DOCKER_BACKEND_PORT=${DOCKER_BACKEND_PORT}
      - DOCKER_POSTGRES_PORT=${DOCKER_POSTGRES_PORT}

      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - ./conf/.env.backend.local
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    build:
      context: ../../
      dockerfile: ./deployments/prod/images/postgres.Dockerfile
    command: ["postgres", "-c", "port=${DOCKER_POSTGRES_PORT}"]
    hostname: ${DOCKER_POSTGRES_HOST}
    expose:
      - ${DOCKER_POSTGRES_PORT}
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - DOCKER_POSTGRES_HOST=${DOCKER_POSTGRES_HOST}
      - DOCKER_POSTGRES_PORT=${DOCKER_POSTGRES_PORT}

      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}",
          "-h",
          "${DOCKER_POSTGRES_HOST}",
          "-p",
          "${DOCKER_POSTGRES_PORT}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  pg-data:
  static_files:
